FROM ubuntu:20.04

ARG USER_ID=501
ARG GROUP_ID=1000

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-get update && apt-get install -y \
    g++-mingw-w64-x86-64 \
    gcc \
    gcc-mingw-w64-x86-64 \
    git \
    wget \
    zip \
    sudo \
    vim \
    nano

# Install PostgreSQL
RUN echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN update-ca-certificates
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-14 sqlite3

USER postgres

# Create Demo Database
COPY docker/scripts/database /var/lib/postgresql/scripts
# RUN /var/lib/postgresql/scripts/createTestDB.sh

WORKDIR $HOME


