FROM node:19

RUN apt-get update && apt-get install -y software-properties-common gcc autoconf automake zlib1g-dev libpng-dev nasm bash libvips-dev git
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/
COPY ../package.json ./package.json
COPY ../package-lock.json ./package-lock.json
RUN npm install -g node-gyp
RUN npm config set fetch-retry-maxtimeout 600000 -g
RUN npm install
ENV PATH /opt/node_modules/.bin:$PATH

WORKDIR /opt/app
COPY ../ .
RUN chown -R node:node /opt/app
USER node
RUN ["npm", "run", "build"]
EXPOSE 1337
CMD ["npm", "run", "develop"]


